"""
Simulation dataset and railway network definitions for the Railway Operations
and Maintenance Visualization Dashboard.
South Indian Rail Corridor: Chennai - Katpadi - Salem - Erode - Coimbatore - Bengaluru.
"""

from typing import Dict, List, Any

# Station Nodes with geographic lat/lng and schematic canvas x/y (1000 x 700 viewBox)
STATIONS_DATA: List[Dict[str, Any]] = [
    {
        "id": "MAS",
        "name": "Chennai Central",
        "code": "MAS",
        "division": "Chennai (MAS)",
        "zone": "Southern Railway",
        "platforms": 12,
        "latitude": 13.0827,
        "longitude": 80.2707,
        "schematic_x": 920,
        "schematic_y": 140,
        "is_junction": True,
    },
    {
        "id": "AJJ",
        "name": "Arakkonam Jn",
        "code": "AJJ",
        "division": "Chennai (MAS)",
        "zone": "Southern Railway",
        "platforms": 5,
        "latitude": 13.0784,
        "longitude": 79.6677,
        "schematic_x": 780,
        "schematic_y": 160,
        "is_junction": True,
    },
    {
        "id": "KPD",
        "name": "Katpadi / Vellore",
        "code": "KPD",
        "division": "Chennai (MAS)",
        "zone": "Southern Railway",
        "platforms": 5,
        "latitude": 12.9698,
        "longitude": 79.1378,
        "schematic_x": 640,
        "schematic_y": 190,
        "is_junction": True,
    },
    {
        "id": "VN",
        "name": "Vaniyambadi",
        "code": "VN",
        "division": "Chennai (MAS)",
        "zone": "Southern Railway",
        "platforms": 3,
        "latitude": 12.6825,
        "longitude": 78.6200,
        "schematic_x": 520,
        "schematic_y": 230,
        "is_junction": False,
    },
    {
        "id": "JTJ",
        "name": "Jolarpettai Jn",
        "code": "JTJ",
        "division": "Chennai (MAS)",
        "zone": "Southern Railway",
        "platforms": 5,
        "latitude": 12.5704,
        "longitude": 78.5772,
        "schematic_x": 420,
        "schematic_y": 280,
        "is_junction": True,
    },
    {
        "id": "BWT",
        "name": "Bangarapet Jn",
        "code": "BWT",
        "division": "Bengaluru (SBC)",
        "zone": "South Western Railway",
        "platforms": 4,
        "latitude": 12.9961,
        "longitude": 78.1969,
        "schematic_x": 380,
        "schematic_y": 190,
        "is_junction": True,
    },
    {
        "id": "KJM",
        "name": "Krishnarajapuram",
        "code": "KJM",
        "division": "Bengaluru (SBC)",
        "zone": "South Western Railway",
        "platforms": 4,
        "latitude": 12.9982,
        "longitude": 77.6834,
        "schematic_x": 280,
        "schematic_y": 150,
        "is_junction": False,
    },
    {
        "id": "SBC",
        "name": "KSR Bengaluru",
        "code": "SBC",
        "division": "Bengaluru (SBC)",
        "zone": "South Western Railway",
        "platforms": 10,
        "latitude": 12.9784,
        "longitude": 77.5684,
        "schematic_x": 190,
        "schematic_y": 120,
        "is_junction": True,
    },
    {
        "id": "HSRA",
        "name": "Hosur",
        "code": "HSRA",
        "division": "Bengaluru (SBC)",
        "zone": "South Western Railway",
        "platforms": 3,
        "latitude": 12.7409,
        "longitude": 77.8253,
        "schematic_x": 220,
        "schematic_y": 230,
        "is_junction": False,
    },
    {
        "id": "DPJ",
        "name": "Dharmapuri",
        "code": "DPJ",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 3,
        "latitude": 12.1277,
        "longitude": 78.1579,
        "schematic_x": 270,
        "schematic_y": 320,
        "is_junction": False,
    },
    {
        "id": "SA",
        "name": "Salem Junction",
        "code": "SA",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 6,
        "latitude": 11.6643,
        "longitude": 78.1460,
        "schematic_x": 350,
        "schematic_y": 420,
        "is_junction": True,
    },
    {
        "id": "ED",
        "name": "Erode Junction",
        "code": "ED",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 5,
        "latitude": 11.3410,
        "longitude": 77.7172,
        "schematic_x": 240,
        "schematic_y": 510,
        "is_junction": True,
    },
    {
        "id": "KRR",
        "name": "Karur Junction",
        "code": "KRR",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 4,
        "latitude": 10.9601,
        "longitude": 78.0766,
        "schematic_x": 410,
        "schematic_y": 570,
        "is_junction": True,
    },
    {
        "id": "TPJ",
        "name": "Tiruchirappalli Jn",
        "code": "TPJ",
        "division": "Tiruchirappalli",
        "zone": "Southern Railway",
        "platforms": 8,
        "latitude": 10.7905,
        "longitude": 78.7047,
        "schematic_x": 550,
        "schematic_y": 620,
        "is_junction": True,
    },
    {
        "id": "TUP",
        "name": "Tiruppur",
        "code": "TUP",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 4,
        "latitude": 11.1085,
        "longitude": 77.3411,
        "schematic_x": 150,
        "schematic_y": 560,
        "is_junction": False,
    },
    {
        "id": "CBE",
        "name": "Coimbatore Jn",
        "code": "CBE",
        "division": "Salem (SA)",
        "zone": "Southern Railway",
        "platforms": 6,
        "latitude": 11.0168,
        "longitude": 76.9558,
        "schematic_x": 70,
        "schematic_y": 610,
        "is_junction": True,
    },
]

# Track Routes connecting stations
ROUTES_DATA: List[Dict[str, Any]] = [
    {
        "id": "R_MAS_AJJ",
        "source_station": "MAS",
        "destination_station": "AJJ",
        "status": "AVAILABLE",
        "distance": 69,
        "capacity": 80,
        "track_count": 4,
        "electrified": "Yes",
        "speed_limit_kmh": 130,
        "category": "Main Trunk",
    },
    {
        "id": "R_AJJ_KPD",
        "source_station": "AJJ",
        "destination_station": "KPD",
        "status": "AVAILABLE",
        "distance": 61,
        "capacity": 70,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 120,
        "category": "Main Trunk",
    },
    {
        "id": "R_KPD_VN",
        "source_station": "KPD",
        "destination_station": "VN",
        "status": "AVAILABLE",
        "distance": 57,
        "capacity": 65,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
    {
        "id": "R_VN_JTJ",
        "source_station": "VN",
        "destination_station": "JTJ",
        "status": "AVAILABLE",
        "distance": 26,
        "capacity": 65,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
    # Jolarpettai -> Bangarapet -> Bengaluru branch
    {
        "id": "R_JTJ_BWT",
        "source_station": "JTJ",
        "destination_station": "BWT",
        "status": "AVAILABLE",
        "distance": 71,
        "capacity": 60,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Bengaluru Branch",
    },
    {
        "id": "R_BWT_KJM",
        "source_station": "BWT",
        "destination_station": "KJM",
        "status": "AVAILABLE",
        "distance": 56,
        "capacity": 60,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Bengaluru Branch",
    },
    {
        "id": "R_KJM_SBC",
        "source_station": "KJM",
        "destination_station": "SBC",
        "status": "AVAILABLE",
        "distance": 14,
        "capacity": 75,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 90,
        "category": "Bengaluru Terminal",
    },
    # Jolarpettai -> Salem Mainline
    {
        "id": "R_JTJ_SA",
        "source_station": "JTJ",
        "destination_station": "SA",
        "status": "AVAILABLE",
        "distance": 120,
        "capacity": 60,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
    # Bengaluru -> Hosur -> Dharmapuri -> Salem Alternative Corridor
    {
        "id": "R_SBC_HSRA",
        "source_station": "SBC",
        "destination_station": "HSRA",
        "status": "AVAILABLE",
        "distance": 52,
        "capacity": 40,
        "track_count": 1,
        "electrified": "Yes",
        "speed_limit_kmh": 90,
        "category": "Bypass Corridor",
    },
    {
        "id": "R_HSRA_DPJ",
        "source_station": "HSRA",
        "destination_station": "DPJ",
        "status": "AVAILABLE",
        "distance": 92,
        "capacity": 40,
        "track_count": 1,
        "electrified": "Yes",
        "speed_limit_kmh": 100,
        "category": "Bypass Corridor",
    },
    {
        "id": "R_DPJ_SA",
        "source_station": "DPJ",
        "destination_station": "SA",
        "status": "AVAILABLE",
        "distance": 63,
        "capacity": 45,
        "track_count": 1,
        "electrified": "Yes",
        "speed_limit_kmh": 100,
        "category": "Bypass Corridor",
    },
    # Salem -> Erode Mainline (will have MB-101 maintenance block scheduled at 11:00 AM)
    {
        "id": "R_SA_ED",
        "source_station": "SA",
        "destination_station": "ED",
        "status": "MAINTENANCE_SCHEDULED",
        "distance": 63,
        "capacity": 65,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
    # Southern Bypass: Salem -> Karur -> Erode
    {
        "id": "R_SA_KRR",
        "source_station": "SA",
        "destination_station": "KRR",
        "status": "AVAILABLE",
        "distance": 85,
        "capacity": 45,
        "track_count": 1,
        "electrified": "Yes",
        "speed_limit_kmh": 100,
        "category": "Alternative Bypass",
    },
    {
        "id": "R_KRR_ED",
        "source_station": "KRR",
        "destination_station": "ED",
        "status": "AVAILABLE",
        "distance": 65,
        "capacity": 45,
        "track_count": 1,
        "electrified": "Yes",
        "speed_limit_kmh": 100,
        "category": "Alternative Bypass",
    },
    {
        "id": "R_KRR_TPJ",
        "source_station": "KRR",
        "destination_station": "TPJ",
        "status": "AVAILABLE",
        "distance": 78,
        "capacity": 50,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 100,
        "category": "Delta Corridor",
    },
    # Erode -> Tiruppur -> Coimbatore
    {
        "id": "R_ED_TUP",
        "source_station": "ED",
        "destination_station": "TUP",
        "status": "AVAILABLE",
        "distance": 50,
        "capacity": 65,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
    {
        "id": "R_TUP_CBE",
        "source_station": "TUP",
        "destination_station": "CBE",
        "status": "AVAILABLE",
        "distance": 50,
        "capacity": 70,
        "track_count": 2,
        "electrified": "Yes",
        "speed_limit_kmh": 110,
        "category": "Main Trunk",
    },
]

# Maintenance Blocks
MAINTENANCE_BLOCKS_DATA: List[Dict[str, Any]] = [
    {
        "id": "MB-101",
        "route_id": "R_SA_ED",
        "location": "Salem \u2192 Erode",
        "source_station": "SA",
        "destination_station": "ED",
        "departments": "Engineering + Signal & Telecom",
        "department_list": ["Engineering", "Signal & Telecom"],
        "activity": "Track Renewal & Point Machine Overhaul",
        "start_time": "11:00",
        "end_time": "15:00",
        "priority": "High",
        "status": "SCHEDULED",
        "estimated_delay_min": 25,
        "alternative_corridor": "Salem \u2192 Karur \u2192 Erode (R_SA_KRR + R_KRR_ED)",
        "allowed_tracks": "Down Line Blocked (Up Line Single Working)",
        "description": "Deep ballast screening, concrete sleeper replacement, and digital axle counter calibration.",
    },
    {
        "id": "MB-102",
        "route_id": "R_KPD_VN",
        "location": "Katpadi \u2192 Vaniyambadi",
        "source_station": "KPD",
        "destination_station": "VN",
        "departments": "Traction / Electrical",
        "department_list": ["Traction / Electrical"],
        "activity": "OHE Catenary Wire Tensioning & Insulator Cleaning",
        "start_time": "07:00",
        "end_time": "09:30",
        "priority": "Medium",
        "status": "COMPLETED",
        "estimated_delay_min": 10,
        "alternative_corridor": "Single Line Bi-directional Dispatch",
        "allowed_tracks": "Up Line OHE Isolated",
        "description": "Routine 25kV overhead electrical wire adjustment and insulator replacement before monsoon.",
    },
    {
        "id": "MB-103",
        "route_id": "R_BWT_KJM",
        "location": "Bangarapet \u2192 Krishnarajapuram",
        "source_station": "BWT",
        "destination_station": "KJM",
        "departments": "Signal & Telecom",
        "department_list": ["Signal & Telecom"],
        "activity": "Electronic Interlocking Software Upgradation",
        "start_time": "13:30",
        "end_time": "16:30",
        "priority": "Medium",
        "status": "SCHEDULED",
        "estimated_delay_min": 15,
        "alternative_corridor": "Manual Pilot Dispatch via Whitefield",
        "allowed_tracks": "Both Tracks Operational with Speed Restriction (30 km/h)",
        "description": "Upgrading relay interlocking to Solid State Electronic Interlocking (EI).",
    },
    {
        "id": "MB-104",
        "route_id": "R_SA_KRR",
        "location": "Salem \u2192 Karur",
        "source_station": "SA",
        "destination_station": "KRR",
        "departments": "Engineering",
        "department_list": ["Engineering"],
        "activity": "Ultrasonic Rail Flaw Detection (USFD)",
        "start_time": "06:00",
        "end_time": "09:30",
        "priority": "Low",
        "status": "COMPLETED",
        "estimated_delay_min": 0,
        "alternative_corridor": "N/A",
        "allowed_tracks": "Single Line Section Clear",
        "description": "High-frequency ultrasonic rail testing for internal transverse fissures.",
    },
]

# Simulated Trains (06:00 to 22:00 schedule)
TRAINS_DATA: List[Dict[str, Any]] = [
    {
        "id": "12641",
        "name": "Kovai Express",
        "type": "Express",
        "origin": "MAS",
        "destination": "CBE",
        "current_route": "R_JTJ_SA",
        "progress_percentage": 42.0,
        "speed": 105,
        "direction": "Down",
        "status": "RUNNING",
        "scheduled_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "SA", "ED", "TUP", "CBE"],
        "alternative_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "SA", "KRR", "ED", "TUP", "CBE"],
        "is_rerouted": False,
        "departure_time": "06:10",
        "expected_arrival": "14:05",
        "delay_minutes": 0,
        "color": "#06b6d4",  # Cyan
    },
    {
        "id": "12675",
        "name": "Cheran Superfast Exp",
        "type": "Express",
        "origin": "CBE",
        "destination": "MAS",
        "current_route": "R_ED_TUP",
        "progress_percentage": 25.0,
        "speed": 110,
        "direction": "Up",
        "status": "RUNNING",
        "scheduled_route": ["CBE", "TUP", "ED", "SA", "JTJ", "VN", "KPD", "AJJ", "MAS"],
        "alternative_route": ["CBE", "TUP", "ED", "KRR", "SA", "JTJ", "VN", "KPD", "AJJ", "MAS"],
        "is_rerouted": False,
        "departure_time": "06:00",
        "expected_arrival": "13:50",
        "delay_minutes": 5,
        "color": "#06b6d4",
    },
    {
        "id": "20607",
        "name": "Vande Bharat Express",
        "type": "Express",
        "origin": "MAS",
        "destination": "SBC",
        "current_route": "R_AJJ_KPD",
        "progress_percentage": 78.0,
        "speed": 130,
        "direction": "Down",
        "status": "RUNNING",
        "scheduled_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "BWT", "KJM", "SBC"],
        "alternative_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "BWT", "KJM", "SBC"],
        "is_rerouted": False,
        "departure_time": "05:50",
        "expected_arrival": "10:20",
        "delay_minutes": 0,
        "color": "#38bdf8",
    },
    {
        "id": "12007",
        "name": "Shatabdi Express",
        "type": "Express",
        "origin": "SBC",
        "destination": "MAS",
        "current_route": "R_JTJ_BWT",
        "progress_percentage": 60.0,
        "speed": 120,
        "direction": "Up",
        "status": "RUNNING",
        "scheduled_route": ["SBC", "KJM", "BWT", "JTJ", "VN", "KPD", "AJJ", "MAS"],
        "alternative_route": ["SBC", "KJM", "BWT", "JTJ", "VN", "KPD", "AJJ", "MAS"],
        "is_rerouted": False,
        "departure_time": "06:00",
        "expected_arrival": "11:00",
        "delay_minutes": 0,
        "color": "#38bdf8",
    },
    {
        "id": "66017",
        "name": "Arakkonam Commuter",
        "type": "Passenger",
        "origin": "MAS",
        "destination": "AJJ",
        "current_route": "R_MAS_AJJ",
        "progress_percentage": 55.0,
        "speed": 65,
        "direction": "Down",
        "status": "RUNNING",
        "scheduled_route": ["MAS", "AJJ"],
        "alternative_route": ["MAS", "AJJ"],
        "is_rerouted": False,
        "departure_time": "09:15",
        "expected_arrival": "10:45",
        "delay_minutes": 2,
        "color": "#10b981",  # Emerald
    },
    {
        "id": "56845",
        "name": "Salem-Erode Passenger",
        "type": "Passenger",
        "origin": "SA",
        "destination": "ED",
        "current_route": "R_SA_ED",
        "progress_percentage": 10.0,
        "speed": 50,
        "direction": "Down",
        "status": "DELAYED",
        "scheduled_route": ["SA", "ED"],
        "alternative_route": ["SA", "KRR", "ED"],
        "is_rerouted": False,
        "departure_time": "10:45",
        "expected_arrival": "12:15",
        "delay_minutes": 35,
        "color": "#10b981",
    },
    {
        "id": "FR-401",
        "name": "CONCOR Container Rake",
        "type": "Freight",
        "origin": "MAS",
        "destination": "CBE",
        "current_route": "R_KPD_VN",
        "progress_percentage": 30.0,
        "speed": 60,
        "direction": "Down",
        "status": "RUNNING",
        "scheduled_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "SA", "ED", "TUP", "CBE"],
        "alternative_route": ["MAS", "AJJ", "KPD", "VN", "JTJ", "SA", "KRR", "ED", "TUP", "CBE"],
        "is_rerouted": False,
        "departure_time": "07:30",
        "expected_arrival": "18:00",
        "delay_minutes": 15,
        "color": "#f59e0b",  # Amber
    },
    {
        "id": "FR-802",
        "name": "NTPC Coal Rake",
        "type": "Freight",
        "origin": "TPJ",
        "destination": "SA",
        "current_route": "R_KRR_TPJ",
        "progress_percentage": 70.0,
        "speed": 55,
        "direction": "Up",
        "status": "RUNNING",
        "scheduled_route": ["TPJ", "KRR", "SA"],
        "alternative_route": ["TPJ", "KRR", "SA"],
        "is_rerouted": False,
        "departure_time": "08:00",
        "expected_arrival": "13:30",
        "delay_minutes": 0,
        "color": "#f59e0b",
    },
    {
        "id": "16382",
        "name": "Kanyakumari Express",
        "type": "Express",
        "origin": "CBE",
        "destination": "SBC",
        "current_route": "R_HSRA_DPJ",
        "progress_percentage": 45.0,
        "speed": 95,
        "direction": "Up",
        "status": "RUNNING",
        "scheduled_route": ["CBE", "TUP", "ED", "SA", "DPJ", "HSRA", "SBC"],
        "alternative_route": ["CBE", "TUP", "ED", "SA", "JTJ", "BWT", "KJM", "SBC"],
        "is_rerouted": False,
        "departure_time": "08:15",
        "expected_arrival": "14:40",
        "delay_minutes": 4,
        "color": "#06b6d4",
    },
]
